### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-67_binding.node":

### ISSUE THREAD

**Issue by ghost** [csstools/postcss-sass#10]
```
npm i -D postcss @csstools/postcss-sass

Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-67_binding.node":

HTTP error 404 Not Found
```
The link is indeed false, linux-x64-64_binding.node is the last available package.

**Comment by ghost** [comment]
Update: had to downgrade to node 10.x from node 11.x

**Comment by jonathantneal** [comment]
@coldtelling, so is the issue with node-sass or exclusively this plugin?

**Comment by ghost** [comment]
Hi,

I'd have to upgrade again and check ! Might be node-sass https://github.com/sass/node-sass/issues/2521

**Comment by jonathantneal** [comment]
Let me know if that worked. Most of the time when people don’t report back, it’s because things are working again, and they must resume their daily work. :)
