### ISSUE TITLE
importer never called

### ISSUE THREAD

**Issue by matthieusieben** [csstools/postcss-sass#16]
It seems there is an issue with `sass` as the `importer()` function never gets called. Switching back to `node-sass` fixes the issue.

**Comment by matthieusieben** [comment]
To test this, simply add the following to the `importer` and run the tests:
```js
	importer(id, parentId, done) {
		console.error('In importer', id)

		// ...
	}
```

You won't see `In importer` in the logs, unless you use `node-sass` (but then, the tests will fail...)

**Comment by chalkygames123** [comment]
As mentioned in https://github.com/maoberlehner/node-sass-magic-importer/issues/191, that is likely due to the `postcss-sass` overriding the `importer` option.

**Comment by matthieusieben** [comment]
What I mean is that postcss-sass 's importer is never called.

Clone this repo, add a log statement **inside postcss-sass** importer and run the tests.

You won't see the log statement.

**Comment by matthieusieben** [comment]
Actually, it seems the importer is called only when `sass` does not find the path by itself using the `includePath`.

**Comment by tsmd** [comment]
AFAIK, this is by design, actually.
Here is designer's comment:
https://github.com/sass/dart-sass/issues/574#issuecomment-457026289

I think you should find another way to build the dependency graph.

**Comment by Steakeye** [comment]
@matthieusieben I forked the library and have a PR, why don't you checkout my version and see if it works for you? I think it solves your problem as I had a similar issue.

**Comment by romainmenke** [comment]
Closing as this is working as the `dart-sass` maintainers intended.
