### ISSUE TITLE
Error with rollup

### ISSUE THREAD

**Issue by drozdzynski** [csstools/postcss-sass#2]
I have rollup plugin for postcss (`rollup-plugin-postcss`),
config:
```
postcss({
  extract: 'main.css',
  plugins: [
    require('@csstools/postcss-sass')(/* node-sass options */)
  ]
}),
```

Error:
```
[!] CssSyntaxError: main.scss:3:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
```

**Comment by jonathantneal** [comment]
Are you using the `postcss-scss` parser? https://github.com/postcss/postcss-scss

For CSS-breaking Sass, PostCSS will require that parser, irrespective of this plugin. Please let me know if using that parser resolves your issue.

Also, would you mind sending me an example of that CSS-breaking Sass? If you do, I’ll include an example in the README.md of this project.

Again, I hope that clears up the issue. 😄

**Comment by drozdzynski** [comment]
I change method of compilation sass so now I can't help.
