### ISSUE TITLE
Unable to recover from root stylesheet errors in imported files

### ISSUE THREAD

**Issue by timkelty** [csstools/postcss-sass#20]
Forgive me if this is a dart-sass problem, but I'm starting here.

I'm running this through `webpack-dev-server`. When I have an error that is triggered on only the "root stylesheet", I have to re-save that file to force a re-compile. Even if the error is actually from an imported file.

Given:

index.scss
```scss
@import './test.scss';
```

test.scss
```scss
body {
  background
}
```

the above will result in an error, and if I resave test.scss with a fix, my css is recompiled and fixed:

```
ERROR in ./src/css/index.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-0-1!./node_modules/postcss-loader/src??ref--7-oneOf-0-2!./src/css/index.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: expected "{".
  ╷
2 │   background;
  │             ^
  ╵
  src/css/test.scss 2:13       root stylesheet
  src/css/index.scss#sass 3:9  root stylesheet
    at Object.BI (/Users/timkelty/Sites/oak/node_modules/sass/sass.dart.js:5233:30)
```

…but if I make an error like this:

```
$foo
body {
  background: red;
}
```

It does not recompile until I re-save the parent (importing) file:
```
ERROR in ./src/css/index.scss (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-0-1!./node_modules/postcss-loader/src??ref--7-oneOf-0-2!./src/css/index.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: expected ":".
   ╷
27 │ $foo
   │     ^
   ╵
  src/css/index.scss#sass 27:5  root stylesheet
    at Object.BI (/Users/timkelty/Sites/oak/node_modules/sass
```

Obv not a huge deal, but a bit of an annoyance when developing. If you think this is a dart-sass issue instead, let me know and I can file there.

UPDATE: I should also mention that I'm using postcss-easy-import, which may be involved…here's my .postscssrc.js:

```js
module.exports = (ctx) => ({
  syntax: 'postcss-scss',
  plugins: {
    'postcss-easy-import': {
        extensions: [
          '.css',
          '.scss'
        ]
      },
    '@csstools/postcss-sass': {},
    'postcss-preset-env': {}
  }
})
```

**Comment by romainmenke** [comment]
This is a chicken vs. egg problem.

This plugin can only know that `test.scss` is a dependency and that re-compilation must happen on changes to that file **after** it has been successfully parsed at least once.

I don't think we can solve this.

**Comment by romainmenke** [comment]
I've tried a few things and this can not be solved.
A file must be successfully parsed for file watching to work.
