### ISSUE TITLE
Please release a new version of the package that includes the new importer parameter

### ISSUE THREAD

**Issue by mlegenhausen** [csstools/postcss-sass#25]
I need this feature to get this package in my project working. It would be nice if you could release it officially.

**Comment by rsmelo92** [comment]
Still waiting!! Whenever you're ready please! Any help you need just call

**Comment by majo44** [comment]
@jonathantneal please :)

**Comment by emilkarl** [comment]
How is it going? would be nice with a release that support PostCSS 8

**Comment by Chaostheorie** [comment]
@jonathantneal a new release would be really appreciated.

**Comment by zavan** [comment]
Just in case anyone needs to get this working before the release, you can install it directly from git:

`yarn add https://github.com/csstools/postcss-sass#master`

or

`npm i https://github.com/csstools/postcss-sass#master`

**Comment by Antonio-Laguna** [comment]
Thanks all for your patience. I've just released 5.0.0
