### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lucacorti** [csstools/postcss-sass#29]
Hi, I appreciate there are other issue open on this, but a few months passed.

I am using a forked version of this repo directly as a dependency, and I guess other people is too.

Is there any plan to cut a new release or is everyone supposed to switch to some other package?

thanks

Luca

**Comment by patrickxchong** [comment]
@lucacorti Can I know which forked version are you using? is it this: https://www.npmjs.com/package/@mozaic-ds/postcss-sass?

**Comment by lucacorti** [comment]
@patrickxchong I'm using https://github.com/sinankeskin/postcss-sass

**Comment by Antonio-Laguna** [comment]
Thanks all for your patience. I've just released 5.0.0
