### ISSUE TITLE
⚠️ Unmaintained

### ISSUE THREAD

**Issue by Antonio-Laguna** [csstools/postcss-sass#30]
This is just a notice that this plugin is mostly unmaintained. This means that there's no one actively developing new features or fixes for it. 

While I see this plugin is popular I just want to acknowledge the situation so it's clear up front. That said, I'm happy to review pull requests that address any bug and do all of the publish process moving forward however as my time (and other's) is limited, we're mostly focusing on plugins under https://github.com/csstools/postcss-plugins

Thank you for your understanding

**Comment by romainmenke** [comment]
I've update all dependencies and working through all issues and pull requests.
Closing this for now.
