### ISSUE TITLE
What's the difference between this and postcss-scss?

### ISSUE THREAD

**Issue by shoyuf** [csstools/postcss-sass#32]

**Comment by yyyanghj** [comment]
I have same question.

I tried `postcss-scss`  in a vite project and it didn't work.

```vue
// vue sfc 

<style lang="postcss">
$blue: #122299;

.foo {
  .bar {
    font-size: 100px;
    font-weight: bold;
    color: $blue;
  }
}
</style>
```


```ts
// vite.config.ts
import * as PostcssScss from "postcss-scss";
export default defineConfig({
  plugins: [vue()],
  css: {
    postcss: {
      parser: PostcssScss, // does not work
    },
  }
})
```

```ts
// vite.config.ts
import sass from '@csstools/postcss-sass'

export default defineConfig({
  plugins: [vue()],
  css: {
    postcss: {
      plugins: [
        sass() // it works well
      ]
    },
  }
})

```

**Comment by binyamin** [comment]
You need both.
1. PostCSS itself only understands vanilla CSS. To _read_ SCSS files, we need to use [`postcss-scss`](https://github.com/postcss/postcss-scss).
    > **This module does not compile SCSS.** It simply parses mixins as custom at-rules & variables as properties, so that PostCSS plugins can then transform SCSS source code alongside CSS.
    > — From the [`postcss-scss` readme](https://github.com/postcss/postcss-scss#readme)
2. Now, plugins can transform the Sass  We're still working with Sass, though.
3. This plugin ([`@csstools/postcss-sass`](https://github.com/csstools/postcss-sass/)) will actually _transform_ the Sass to CSS, using dart-sass itself.

**Example**: postcss.config.js
```js
import sassSyntax from 'postcss-scss';
import sassPlugin from '@csstools/postcss-sass';

export default {
    syntax: sassSyntax,
    plugins: [
        sassPlugin({
            // The options are the same as for `sass.render`
        })
        // ...more plugins
    ]
}

**Comment by romainmenke** [comment]
This is documented in the README here : https://github.com/csstools/postcss-sass#postcss

**Comment by vhscom** [comment]
> This is documented in the README

Where has this maybe documented it still is unclear even to me and I've been developing web apps for 15 years. To reduce the amount of confusion users feel when they learn about living node sass being deprecated and the presence of this plugin in addition to the replacement dart sass then add in the confusing terms pre and post processing and I can understand how people will get confused unless things are specifically spelled out in detail. while there is some detail currently providing use cases might be helpful. This of course is not the job of this library but I have not been able to find any blog posts covering this addon in much detail.
