### ISSUE TITLE
types

### ISSUE THREAD

**Issue by AllanOricil** [csstools/postcss-sass#42]
I can't use it in a typescript project without types

<img width="1589" alt="image" src="https://github.com/user-attachments/assets/eacae792-28ff-465a-a6b2-fe389088bfbc">

## Workaround

```typescript
// @ts-ignore
import postcssSass from "@csstools/postcss-sass";
```

**Comment by romainmenke** [comment]
Sorry, just use the workaround, not going to add types to this package.
