### ISSUE TITLE
Example showing how to use with postcss-scss

### ISSUE THREAD

**Issue by JoyceBabu** [csstools/postcss-sass#8]
The current example fails when used with a `.scss` file with error

> You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

Can you please include an example showing how to use the plugin with postcss-scss?

**Comment by jonathantneal** [comment]
That’s a really good catch, @JoyceBabu, since Sass files can contain comments and markup that would fail in the standard CSS parser.

Thanks for telling me, and I hope you didn’t lose too much time figuring it out for yourself.

If you have time to make a PR, it would be appreciated, but otherwise I will try to get to this soon.

**Comment by JoyceBabu** [comment]
I just figured out how to compile it. 

```
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var scss = require('postcss-scss');

gulp.task('css', function () {
  return gulp.src('src/*.scss').pipe(
    postcss([
      require('@csstools/postcss-sass')(/* node-sass options */)
    ], {syntax: scss})
  ).pipe(
    gulp.dest('test')
  );
});
```

I just realised that `sass` and `scss` are different syntaxes. But I don't understand the use case for using `@csstools/postcss-sass` without `postcss-scss` / `postcss-sass` syntax. Also, I don't understand why the standard css parser did not throw any error with the example that you have given, as it is not valid CSS.

Is there any advantage to using `scss` syntax and `@csstools/postcss-sass` to transform my SCSS files, over compiling the source css using `gulp-sass` directly, before passing to `postcss`?

**Comment by JoyceBabu** [comment]
Also,  it is not playing well with `cssnano` plugin.

**Comment by jonathantneal** [comment]
cssnano has a lot of issues. I can’t support it.

Recent example: https://twitter.com/Jon_Milner/status/1051926288963919872

**Comment by jonathantneal** [comment]
> I don't understand the use case for using @csstools/postcss-sass without postcss-scss / postcss-sass syntax

Plugins can’t dictate your syntax. I can recommend it in the README.md, but that’s it. This plugin can’t make PostCSS use a different parser.

> I don't understand why the standard css parser did not throw any error with the example that you have given, as it is not valid CSS.

A lot of “invalid” CSS is parsed fine by CSS. Namely, it’s the Sass `// comments` that regular CSS chokes on.

> Is there any advantage to using scss syntax and @csstools/postcss-sass to transform my SCSS files, over compiling the source css using gulp-sass directly, before passing to postcss?

Yes, better source maps and control over plugin order.

**Comment by JoyceBabu** [comment]
> cssnano has a lot of issues. I can’t support it.

Do you have any recommendations a better minifier?

> Plugins can’t dictate your syntax. I can recommend it in the README.md, but that’s it. This plugin can’t make PostCSS use a different parser.

Does that mean that the plugin is intended to be used with either of `postcss-scss` or `postcss-sass` normally?

> Yes, better source maps and control over plugin order.

Thank you for the information.

**Comment by jonathantneal** [comment]
> Does that mean that the plugin is indeed intended to be used with either of postcss-scss or postcss-sass normally?

It depends. I haven’t write Sass that is CSS incompatible in years. I guess your mile-age my vary. I’m closing this issue, but I’m open to a PR to update the docs to include an example where one configures a sass parser for PostCSS.

> Do you have any recommendations a better minifier?

No. cssnano has a lot of issues, and is also the best minifier out there. I think new people have recently been working on the project, and updates may be coming out soon. I just don’t want to get caught up supporting cssnano and taking on another dependency. I would never get sleep. :)
